[accessibility]
ui_scale = 1.1000000089406967

[bar]
order = [ "topbar" ]

    [bar.topbar]
    center = [ "date", "clock" ]
    end = [ "tray", "network", "bluetooth", "brightness", "input_volume", "output_volume", "battery" ]
    font_family = "Google Sans Medium"
    margin_ends = 0
    padding = 16
    radius = 0
    radius_bottom_left = 12
    radius_bottom_right = 12
    scale = 1.2000000104308128
    start = [ "session", "workspaces" ]

[battery]
warning_threshold = 20

[control_center]
sidebar_section = "none"
width = 900

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
pre_action_fade_seconds = 0

[location]
auto_locate = true

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 1536.0
    cy = 1529.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 1024.0
    cy = 1081.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[nightlight]
enabled = true

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/home/vgonz/Pictures/Wallpapers"

[plugins]
enabled = [ "noctalia/translator", "blackbartblues/audio-switcher", "noctalia/mpvpaper" ]

[shell]
avatar_path = "/home/vgonz/Pictures/solid_snake_001.jpg"
button_borders = false
font_family = "Google Sans"
lang = "en"

    [shell.launcher]
    categories = false

    [shell.panel]
    session_placement = "floating"
    session_position = "center"

    [shell.screenshot]
    directory = "/home/vgonz/Pictures/Screenshots"

    [shell.session]
    grid_columns = 4
    show_shortcuts = false

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

[system.monitor]
enabled = false

[theme]
builtin = "Gruvbox"
community_palette = "Catppuccin Mocha Lavender"
mode = "dark"
source = "community"

    [theme.templates]
    builtin_ids = [ "btop", "hyprland", "kitty", "starship" ]
    community_ids = [ "yazi" ]

[wallpaper]
transition = []
transition_on_startup = true

    [wallpaper.default]
    path = "/home/vgonz/Pictures/Wallpapers/import-4fe31cfb-98b2-458b-a7f4-bb65b060a9b7.png"

    [wallpaper.last]
    path = "/home/vgonz/Pictures/Wallpapers/import-4fe31cfb-98b2-458b-a7f4-bb65b060a9b7.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/vgonz/Pictures/Wallpapers/import-4fe31cfb-98b2-458b-a7f4-bb65b060a9b7.png"

[widget.battery]
display_mode = "graphic"
scale = 0.80000000000000004

[widget.bluetooth]
capsule_radius = 8
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.date]
enabled = false
format = "{:%d/%m}"

[widget.input_volume]
mute_color = "on_surface"
scale = 0.94999999999999996
show_label = false

[widget.launcher]
enabled = false

[widget.network]
capsule_radius = 8
show_label = false
show_vpn_label = true
vpn_status = "both"

[widget.output_volume]
mute_color = "on_surface"
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.wallpaper]
enabled = false

[widget.workspaces]
active_pill_size = 2.6000000000000001
capsule_radius = "auto"
display = "none"
hide_when_empty = true
inactive_pill_size = 1.3
